version: "2.1"

services:
  web:
    container_name: "sc-api-applications"
    build: .
    command: pm2-docker ./src/process.json
    volumes:
      - ./src:/src
      - ./test:/test
    environment:
        - NODE_ENV=development
        - CLIENT_HOST=app.frontend
        - CLIENT_PORT=80
        - CLIENT_PROTOCOL=http
        - DEBUG_PORT=5858
    ports:
      - "4001:80"
      - "5001:5858"
    restart: on-failure
    network_mode: "webnet"
